stages:
  - build
  - test
  - release

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  TF_BASE_VERSION: 1.5.1

build:
  image: tensorflow/tensorflow:${TF_BASE_VERSION}-devel-gpu-py3
  stage: build
  before_script:
    - pip install conan invoke
    - conan profile new default --detect
    - conan profile update settings.compiler.libcxx=libstdc++11 default
  script:
    - inv init --no-edit
    - cat invoke.yml
    - inv ci --ref ${CI_COMMIT_REF_NAME}
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ${CI_PROJECT_DIR}/dist/*.zip
      - ${CI_PROJECT_DIR}/dist/*.whl
    expire_in: 1 week

test-pyimport:
  stage: test
  image: tensorflow/tensorflow:${TF_BASE_VERSION}-gpu-py3
  tags:
    - gpu
  script:
    # We need to get out of the tensorflow source folder, otherwise import won't work
    - pip install ${CI_PROJECT_DIR}/dist/*.whl
    - python -c 'import tensorflow'

test-tfsrc:
  stage: test
  script:
    - test -d dist/devel/bazel-genfiles
    - test -d dist/devel/bazel-tensorflow/tensorflow/core
    - test -d dist/devel/bazel-tensorflow/tensorflow/cc
    - test -d dist/devel/bazel-tensorflow/third_party
    - test -d dist/devel/bazel-bin/tensorflow
    - test -f dist/devel/bazel-tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor
    - test -f dist/devel/bazel-tensorflow/external/eigen_archive/unsupported/Eigen/CXX11/Tensor
    - test -f dist/devel/bazel-bin/tensorflow/libtensorflow_framework.so
    - test -f dist/devel/bazel-bin/tensorflow/libtensorflow_kernels.so

release:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $LATEST_TAG
    - docker push $LATEST_TAG
  only:
    - master
  artifacts:  # keep the artifacts (default expire forever)
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - ${CI_PROJECT_DIR}/dist/*.zip
      - ${CI_PROJECT_DIR}/dist/*.whl
