stages:
  - build
  - test
  - release

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  TF_BASE_VERSION: 1.5.1
  CONAN_LOGIN_USERNAME: peifeng
  # CONAN_PASSWORD is set in project settings

build:
  image: tensorflow/tensorflow:${TF_BASE_VERSION}-devel-gpu-py3
  stage: build
  # need to run on our self-hosted machine otherwise times out on gitlab agents
  tags:
    - gpu
  before_script:
    - pip install conan invoke
    - conan profile new default --detect
    - conan profile update settings.compiler.libcxx=libstdc++11 default
  script:
    - inv init --no-edit
    - cat invoke.yml
    - inv conan-login
    - inv ci-build --ref "${CI_COMMIT_SHA}"
    - inv conan-upload
  artifacts:
    name: "${CI_PROJECT_NAME}-${TF_BASE_VERSION}-${CI_COMMIT_SHA}"
    paths:
      - ${CI_PROJECT_DIR}/dist/*.whl
    expire_in: 1 week

test-pyimport:
  stage: test
  image: tensorflow/tensorflow:${TF_BASE_VERSION}-gpu-py3
  tags:
    - gpu
  script:
    - pip install ${CI_PROJECT_DIR}/dist/*.whl
    # We need to get out of the tensorflow source folder, otherwise import won't work
    - cd / && python -c 'import tensorflow'

release:
  stage: release
  before_script:
    - pip install conan invoke
  script:
    - inv conan-login
    - inv conan-promote --ref "${CI_COMMIT_SHA}"
    - inv conan-upload
  only:
    - master
  artifacts:  # keep the artifacts passed from previous stage (default expire forever)
    name: "${CI_PROJECT_NAME}-${TF_BASE_VERSION}"
    paths:
      - ${CI_PROJECT_DIR}/dist/*.whl
