image: docker:latest
stages:
  - build
  - test
  - release

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  services:
    - docker:dind
  tags:
    - gpu
  script:
    - spack install 


unittest:
  tags:
    - gpu-p100
  script:
    - echo
